// @ts-nocheck -- this is the wrangler/OpenNext Worker entrypoint, compiled
// by wrangler's own esbuild pipeline during `opennextjs-cloudflare build`,
// never by `next build`'s tsc pass. It imports ./.open-next/worker.js,
// which is generated by that same build step and legitimately does not
// exist yet when `next build` runs on its own -- tsconfig's `exclude`
// doesn't stop Next's typecheck from still walking this file, so ts-nocheck
// is the actual fix.
import { Container } from "@cloudflare/containers";
import { default as handler } from "./.open-next/worker.js";

/* The OpenNext-generated worker only exports a fetch handler. Adding the
   render-service container binding (see wrangler.jsonc's `containers` /
   `durable_objects`) requires a custom Worker entrypoint that re-exports
   that handler and additionally exports this Durable Object class --
   Cloudflare's documented pattern for extending an OpenNext app with
   bindings it doesn't generate on its own. */
export class RenderContainer extends Container {
  defaultPort = 8080;
  sleepAfter = "2m";
}

/* The official Gotenberg image (see wrangler.jsonc), configured to require
   basic auth. Its username/password come from this Worker's own secrets
   (`wrangler secret put GOTENBERG_USERNAME` / `GOTENBERG_PASSWORD`) set at
   construction time -- never hardcoded here or in wrangler.jsonc. */
export class GotenbergContainer extends Container {
  defaultPort = 3000;
  sleepAfter = "5m";

  constructor(ctx, env) {
    super(ctx, env);
    this.envVars = {
      API_ENABLE_BASIC_AUTH: "true",
      GOTENBERG_API_BASIC_AUTH_USERNAME: env.GOTENBERG_USERNAME,
      GOTENBERG_API_BASIC_AUTH_PASSWORD: env.GOTENBERG_PASSWORD,
    };
  }
}

export default {
  fetch: handler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
